---
- name: Install Commons Packages
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - '{{ common_packages }}'
  become: yes

- name: Create Commons Paths (logs, update)
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
  loop: '{{ paths }}'
  become: yes

- name: Set LD_LIBRARY_PATH Variable
  shell: |
      echo export LD_LIBRARY_PATH=\
      '{{ lockserver_path }}':\
      '{{ license_appserver_path }}':\
      '{{ dbaccess_bin_path }}':\
      '{{ broker_path }}':\
      '{{ slave01_path }}':\
      '{{ slave02_path }}':\
      '{{ soap_path }}':\
      '{{ rest_path }}' >> ~/.bash_profile
      source ~/.bash_profile