---
- name: Install Commons Packages
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - '{{ common_packages }}'
  become: yes

- name: Create Commons Paths (logs, update)
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
  loop: '{{ paths }}'
  become: yes

- name: Set LD_LIBRARY_PATH Variable
  template:
    src: .bash_profile.j2
    dest: ~/.bash_profile
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    force: yes
  become: yes

- name: Set Bash Profile
  shell: |
     source ~/.bash_profile
  become: yes