---
- name: Create Dictionary Paths
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - '{{ system_path }}'
    - '{{ systemload_path }}'
    - '{{ web_path }}'
    - '{{ portaL_rh_path }}'
  become: yes

- name: Copy License Files
  copy:
    src: license.zip
    dest: '{{ app_path }}'
    mode: '0775'
  become: yes

- name: Extract License Files
  unarchive:
    src: '{{ app_path }}/license.zip'
    dest: '{{ app_path }}'
    remote_src: yes
  become: yes

- name: Clear License Files
  file:
    path: '{{ app_path }}/license.zip'
    state: absent
  become: yes