---
- name: Copy License Files
  copy:
    src: license.zip
    dest: '{{ app_path }}'
    mode: '0775'
  become: yes

- name: Extract License Files
  unarchive:
    src: '{{ app_path }}/license.zip'
    dest: '{{ app_path }}'
    remote_src: yes
  become: yes

- name: Copy Script for Maintenance(Stop,Start,Restart, Status)
  template:
    src: totvslicense.j2
    dest: '{{ script_path}}/totvslicense'
    owner: vagrant
    group: vagrant
    mode: 0775
  with_items:
    - '{{ templates }}'
  become: yes

- name: Clear License Files
  file:
    path: '{{ app_path }}/license.zip'
    state: absent
  become: yes