---
- name: Copy License Files
  copy:
    src: license.zip
    dest: '{{ app_path }}'
    mode: '0775'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
  become: yes

- name: Extract License Files
  unarchive:
    src: '{{ app_path }}/license.zip'
    dest: '{{ app_path }}'
    remote_src: yes
  become: yes

- name: Copy Appserver.ini
  template:
    src: appserver.ini.j2
    dest: '{{ license_appserver_path }}/appserver.ini'
    owner: vagrant
    group: vagrant
    mode: 0775
  become: yes

- name: Set License Bin Name
  copy:
    src: '{{ license_appserver_path }}/appsrvlinux'
    dest: '{{ license_appserver_path }}/app_license'
    owner: vagrant
    group: vagrant
    mode: '0775'
    remote_src: yes

- name: Copy Script for Maintenance(Stop,Start,Restart, Status)
  template:
    src: totvslicense.j2
    dest: '{{ script_path}}/totvslicense'
    owner: vagrant
    group: vagrant
    mode: 0775
  become: yes

- name: Clear License Files
  file:
    path: '{{ app_path }}/license.zip'
    state: absent
  become: yes