# - hosts: postgresql
#   become: yes
#   vars_files:
#     - roles/postgresql/vars/main.yml
#   roles:
#     - postgresql

- hosts: protheus
  become: yes
  roles:
    - common
    # - rpo
    # - dictionary